version: "3.7"

services:
  # Application
  gpa_calculator:
    build:
      context: .
      dockerfile: Dockerfile
    image: gpa_calculator:latest
    command: ./scripts/run-server.sh
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    container_name: gpa_calculator

volumes:
  gpa_calculator_data:
